export const PROVINCES: string[] = ['Antalya']

export const DISTRICTS_BY_PROVINCE: Record<string, string[]> = {
    Antalya: ['Aksu', 'Döşemealtı', 'Kepez', 'Konyaaltı', 'Muratpaşa', 'Akseki', 'Alanya', 'Demre', 'Elmalı', 'Finike', 'Gazipaşa', 'Gündoğmuş', 'İbradı', 'Kaş', 'Kemer', 'Korkuteli', 'Kumluca', 'Manavgat', 'Serik'],
}

export const NEIGHBORHOODS_BY_DISTRICT: Record<string, string[]> = {
    Aksu: ['Alaylı', 'Altıntaş', 'Atatürk', 'Barbaros', 'Boztepe', 'Cihadiye', 'Cumhuriyet', 'Çalkaya', 'Çamköy', 'Dumanlar', 'Fatih', 'Fettahlı', 'Gökdere', 'Güloluk', 'Güzelyurt', 'Hacıaliler', 'İhsaniye', 'Karaçallı', 'Karaöz', 'Kayadibi', 'Kemerağzı', 'Konak', 'Kumköy', 'Kundu', 'Kurşunlu', 'Macun', 'Mandırlar', 'Murtuna', 'Pınarlı', 'Soğucaksu', 'Solak', 'Topallı', 'Yenidumanlar', 'Yeşilkaraman', 'Yurtpınar'],
    Döşemealtı: ['Ahırtaş', 'Akkoç', 'Altınkale', 'Aşağıoba', 'Ayanlar', 'Aydınlar', 'Bademağacı', 'Bahçeyaka', 'Bıyıklı', 'Camili', 'Çığlık', 'Çıplaklı', 'Dağbeli', 'Dereli', 'Düzlerçamı', 'Ekşili', 'Ilıcaköy', 'Karaman', 'Karataş', 'Karaveliler', 'Kevşirler', 'Killik', 'Kovanlık', 'Kömürcüler', 'Nebiler', 'Orta', 'Selimiye', 'Tomalar', 'Yağca', 'Yalınlı', 'Yeniköy', 'Yeşilbayır'],
    Kepez: ['Ahatlı','Aktoprak','Altıayak','Altınova Düden','Altınova Orta','Altınova Sinan','Atatürk','Avni Tolunay','Ayanoğlu','Aydoğmuş','Baraj','Barış','Başköy','Beşkonaklılar','Çamlıbel','Çamlıca','Çankaya','Demirel','Duacı','Duraliler','Düdenbaşı','Emek','Erenköy','Esentepe','Fabrikalar','Fatih','Fevzi Çakmak','Gazi','Gaziler','Göçerler','Göksu','Gülveren','Gündoğdu','Güneş','Habibler','Hüsnü','Karakaş','Kanal','Karşıyaka','Kazım Karabekir','Kepez','Kızıllı','Kirişçiler','Kuzeyyaka','Kültür','Kütükçü','Mehmet Akif Ersoy','Menderes','Odabaşı','Özgürlük','Santral','Sütçüler','Şafak','Şelale','Teomanpaşa','Ulus','Ünsal','Varsak Esentepe','Varsak Karşıyaka','Varsak Menderes','Yavuz Selim','Yenimahalle','Yenidoğan','Yeniemek','Yeşiltepe','Yeşilyurt','Yükseliş','Zafer','Zeytinlik'],
    Konyaaltı: ['Akdamlar','Akkuyu','Altınkum','Arapsuyu','Aşağıkaraman','Aydınlık','Bahtılı','Çağlarca','Çakırlar','Çitdibi','Demircilik','Doyran','Doyran Çamlıbel','Doyran Dağ','Geyikbayırı','Gökçam','Gökdere','Gürsu','Hacısekililer','Hisarçandır','Hurma','Karatepe','Kır','Kuruçay','Kuşkavağı','Liman','Molla Yusuf','Öğretmenevleri','Pınarbaşı','Sarısu','Siteler','Suiçecek','Toros','Uluç','Uncalı','Üçoluk','Yarbaşçandır','Yenimahalle','Zümrüt'],
    Muratpaşa: ['Altındağ','Bahçelievler','Balbey','Barbaros','Bayındır','Cumhuriyet','Çağlayan','Çaybaşı','Demircikara','Deniz','Doğuyaka','Dutlubahçe','Elmalı','Ermenek','Etiler','Fener','Gebizli','Gençlik','Güvenlik','Güzelbağ','Güzeloba','Güzeloluk','Haşimişcan','Kılınçarslan','Kırcami','Kışla','Kızılarık','Kızılsaray','Kızıltoprak','Konuksever','Mehmetçik','Meltem','Memurevleri','Meydankavağı','Muratpaşa','Sedir','Selçuk','Sinan','Soğuksu','Şirinyalı','Tahılpazarı','Tarım','Topçular','Tuzcular','Üçgen','Varlık','Yenigöl','Yenigün','Yeşilbahçe','Yeşildere','Yeşilova','Yıldız','Yüksekalan','Zerdalilik','Zümrütova'],
    Akseki: ['Akşahap','Alaçeşme','Aşağıaşıklar','Bademli','Belenalan','Boğaz','Bucakalan','Ceceler','Cemerler','Cendeve','Cevizli','Çaltılıçukur','Çanakpınar','Çınardibi','Çimiköy','Çukurköy','Değirmenlik','Demirciler','Dikmen','Dutluca','Emiraşıklar','Erenyaka','Fakılar','Geriş','Güçlüköy','Gümüşdamla','Güneykaya','Günyaka','Güzelsu','Hacı İlyas','Hocaköy','Hüsamettinköy','Karakışla','Kepez','Kepezbeleni','Kuyucak','Mahmutlu','Menteşbey','Minareli','Pınarbaşı','Sadıklar','Salihler','Sarıhacılar','Sarıhaliller','Sinanhoca','Susuzşahap','Süleymaniye','Taşlıca','Yarpuz'],
    Alanya: ['Akçatı','Akdam','Alacami','Alara','Aliefendi','Asmaca','Avsallar','Bademağacı','Basırlı','Başköy','Bayırköy','Bayırkozağacı','Bektaş','Beldibi','Beyreli','Bıçakçı','Bucakköy','Burçaklar','Büyükhasbahçe','Büyükpınar','Cikcilli','Cumhuriyet','Çakallar','Çamlıca','Çarşı','Çıplaklı','Değirmendere','Demirtaş','Dereköy','Dinek','Elikesik','Emişbeleni','Fakırcalı','Fığla','Gözübüyük','Gözüküçüklü','Güllerpınarı','Gümüşgöze','Gümüşkavak','Güneyköy','Güzelbağ','Hacet','Hacıkerimler','Hacımehmetli','Hisariçi','Hocalar','İmamlı','İncekum','İspatlı','İshaklı','Kadıpaşa','Karakocalı','Karamanlar','Karapınar','Kargıcak','Kayabaşı','Kestel','Keşefli','Kızılcaşehir','Kızlarpınarı','Kocaoğlanlı','Konaklı','Kuzyaka','Küçükhasbahçe','Mahmutlar','Mahmutseydi','Oba','Obaalacami','Okurcalar','Orhanköy','Öteköy','Özvadi','Paşaköy','Payallar','Saburlar','Sapadere','Saray','Seki','Soğukpınar','Sugözü','Süleymanlar','Şekerhane','Şeyhler','Taşbaşı','Tepe','Tırılar','Tophane','Toslak','Tosmur','Türkler','Türktaş','Uğrak','Uğurlu','Uzunöz','Üzümlü','Yalçı','Yasırali','Yaylakonak','Yaylalı','Yenice','Yeniköy','Yeşilöz'],
    Demre: ['Alakent','Belören','Beymelek','Büyükkum','Çağman','Çevreli','Davazlar','Gökyazı','Gürses','Kaleüçağız','Kapaklı','Karabucak','Kayaaltı','Köşkerler','Küçükkum','Yavu','Yaylakaya'],
    Elmalı: ['Camiatik','Camicedit','Gündoğan','İplikpazarı','Kapmescit','Karyağdı','Tahtamescit','Toklular','Yeni','Afşar','Ahatlı','Akçaeniş','Akçay','Armutlu','Bayındır','Bayralar','Beyler','Bozhüyük','Büyüksöğle','Çaybaşı','Çobanisa','Çukurelma','Dereköy','Düdenköy','Eskihisar','Eymir','Geçitköy','Geçmen','Gökpınar','Göltarla','Gümüşyaka','Hacımusalar','Hacıyusuflar','İlyağı','İmircik','İslamlar','Karaköy','Karamık','Kışlaköy','Kızılca','Kocapınar','Kuzköy','Küçüksöğle','Macun','Mursal','Müren','Ovacık','Özdemir','Pirhasanlar','Salur','Sarılar','Tavullar','Tekkeköy','Yakaçiftlikköyü','Yalnızdam','Yapraklı','Yılmazlı','Yörenler','Yuva','Zümrütova'],
    Finike: ['Akçaalan','Alacadağ','Arif','Asarönü','Boldağ','Çamlıbel','Dağbağ','Ernez','Eski','Gökbük','Gökçeyaka','Hasyurt','İskele','Kale','Karşıyaka','Kızılca','Kum','Sahilkent','Saklısu','Turunçova','Yalnız','Yazır','Yeni','Yeşilköy','Yeşilyurt','Yuvalı'],
    Gazipaşa: ['Akoluk','Aydın','Aydıncık','Bakılar','Beyobası','Beyrebucak','Cumhuriyet','Çakmak','Çalıpınar','Çamlıca','Çığlık','Çile','Çimenbağ','Çobanlar','Çörüş','Doğanca','Ekmel','Esenpınar','Esentepe','Gazi','Göçük','Gökçebelen','Gökçesaray','Güneyköy','Gürçam','Hasdere','Ilıcaköy','İnalköy','İnceğiz','İstiklal','Kahyalar','Karaçukur','Karalar','Karatepe','Kırahmetler','Kızılgüney','Koru','Korubaşı','Küçüklü','Macarköy','Muzkent','Öznurtepe','Pazarcı','Sarıağaç','Sugözü','Şahinler','Üçkonak','Yakacık','Yeni','Yenigüney','Yeniköy','Yeşilyurt','Zeytinada'],
    Gündoğmuş: ['Akyar','Balkaya','Bedan','Çaltı','Çamlıalan','Çayırözü','Çiçekoluk','Eskibağ','Fatih','Güneycik','Güneyyaka','Kalecik','Karabul','Karadere','Karaisa','Karaköy','Kayabükü','Kozağacı','Köprülü','Narağacı','Ortakonuş','Ortaköy','Özügür','Pembelik','Rasih','Kaplan','Senir','Serinyaka','Umutlu','Yeniköy'],
    İbradı: ['Aşağı','Aydınyayla', 'Başlar','Çukurviran','Düzlen','Ormana','Ürünlü','Üzümdere','Yukarı'],
    Kaş: ['Ağullu','Ahatlı','Aklar','Akörü','Andifli','Bayındır','Beldibi','Belenli','Belkonak','Bezirgan','Cemre','Çamlıköy','Çamlıova','Çataloluk','Çavdır','Çayköy','Çerler','Çeşmeköy','Çukurbağ','Dereköy','Dirgenler','Doğantaş','Gelemiş','Gökçeören','Gökçeyazı','Gömbe','Gürsu','Hacıoğlan','İkizce','İslamlar','Kalkan','Karadağ','Kasaba','Kemerköy','Kınık','Kızılağaç','Ortabağ','Ova','Palamutköy','Pınarbaşı','Sahil','Barak','Sahilkılınçlı','Sarıbelen','Sarılar','Sinneli','Sütleğen','Uğrar','Üzümlü','Yaylakılınçlı','Yaylapalamut','Yeniköy','Yeşilbarak','Yeşilköy','Yuvacık'],
    Kemer: ['Arslanbucak','Beldibi','Beycik','Çamyuva','Göynük','Kiriş','Kuzdere','Merkez','Ovacık','Tekirova','Ulupınar','Yenimahalle','Çıralı'],
    Korkuteli: ['Alaaddin','Aşağıpazar','Kargalık','Karşıyaka','Kiremitli','Uzunoluk','Yenimahalle','Akyar','Avdan','Bahçeyaka','Bayat','Bayatbademleri','Beğiş','Bozova','Büyükköy','Çaykenarı','Çıvgalar','Çomaklı','Çukurca','Dereköy','Duraliler','Esenyurt','Garipce','Göçerler','Güzle','İmecik','İmrahor','Karabayır','Karakuyu','Karataş','Kargın','Kayabaş','Kemerağzı','Kevzer','Kırkpınar','Kızılaliler','Kızılcadağ','Kozağacı','Köseler','Küçükköy','Küçüklü','Leylekköyü','Mamatlar','Manay','Nebiler','Osmankalfalar','Sımandır','Söbüce','Söğütcük','Sülekler','Taşkesiği','Tatköy','Yakaköy','Yalınlıgediği','Yazır','Yeleme','Yelten','Yeşiloba','Yeşilyayla','Yukarıkaraman'],
    Kumluca: ['Adrasan','Altınyaka','Bağlık','Belen','Beşikçi','Beykonak','Büyükalan','Cumhuriyet','Çaltı','Çayiçi','Dereköy','Ellinci Yıl','Erentepe','Eskicami','Göksu','Gölcük','Güzören','Hacıveliler','Hızırkahya','İncircik','Karacaağaç','Karacaören','Karşıyaka','Kasapçayırı','Kavakköy','Kum','Kuzca','Mavikent','Merkez','Meydan','Narenciye','Ortaköy','Salur','Sarıcasu','Sarıkavak','Temel Eğitim','Toptaş','Yazır','Yenikışla','Yenimahalle','Yeşilköy'],
    Manavgat: ['Ahmetler','Aksaz','Altınkaya','Aşağı Işıklar','Aşağıhisar','Aşağıpazarcı','Aydınevler','Bahçelievler','Ballıbucak','Belenobası','Bereket','Beşkonak','Beydiğin','Boztepe','Bucakşeyhler','Burmahan','Büklüce','Cevizler','Çağlayan','Çakış','Çaltepe','Çardakköy','Çavuşköy','Çayyazı','Çeltikçi','Çenger','Çolaklı','Demirciler','Denizkent','Denizyaka','Dikmen','Doğançam','Dolbazlar','Düzağaç','Emek','EskiHisar','Evrenleryavşı','Evrenseki','Gaziler','Gebece','Gençler','Gültepe','Gündoğdu','Güzelyalı','Hacıali','Hacıisalı','Hacıobası','Halitağalar','Hatipler','Hocalar','Hocalı','Ilıca','Kadılar','Kalemler','Karabucak','Karabük','Karacalar','Karakaya','Karaöz','Karavca','Kasaplar','Kavaklı','Kırkkavak','Kısalar','Kızılağaç','Kızıldağ','Kızılot','Milli Egemenlik','Mimarsinan','Namaras','Odaönü','Oymapınar','Örenşehir','Örnek','Perakende','Sağırin','SalkımEvler','Salur','Sanayi','Saraçlı','Sarılar','Sevinçköy','Seydiler','Sırtköy','Side','Sorgun','Sülek','Şelale','Şişeler','Taşağıl','Taşkesiği','Tepeköy','Tilkiler','Ulukapı','Uzunkale','Uzunlar','Yalçıdibi','Yavrudoğan','Yayla','Yaylaalan','Yeniköy','Yeşilbağ','Yukarı Işıklar','Yukarıhisar','Yukarıpazarcı'],
    Serik: ['Abdurrahmanlar','Akbaş','Akçaalan','Akçapınar','Alacami','Aşağıçatma','Aşağıkocayatak','Aşağıoba','Belek','Belkıs','Belpınar','Berendi','Bilginler','Boğazkent','Bozdoğan','Bucakköy','Burmahancı','Büğüş','Cumalı','Cumhuriyet','Çakallık','Çanakçı','Çandır','Çatallar','Demirciler','Deniztepesi','Dikmen','Dorumlar','Eminceler','Eskiyürük','Etler','Gebiz','Gedik','Gökçepınar','Hacıosmanlar','Hasdümen','Haskızılören','Haspınar','Kadriye','Karadayı','Karataş','Karıncalı','Kayaburnu','Kırbaş','Kozağacı','Kozan','Kökez','Kuşlar','Kürüş','Merkez','Nebiler','Orta','Pınarcık','Sarıabalı','Şatırlı','Tekke','Töngüşlü','Üründü','Yanköy','Yenimahalle','Yeşilvadi','Yeşilyurt','Yukarıçatma','Yukarıkocayatak','Yumaklar','Zırlankaya']

}


